name: Deploy to k3s

on:
  workflow_run:
    workflows: ["Flask Sample App CI/CD Workflow"]  # CI workflow name
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Flask app to k3s
        run: |
          # Ensure kubectl sees the kubeconfig
          export KUBECONFIG=~/.kube/config

          # Apply Kubernetes manifests
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml

      - name: Verify deployment
        run: |
          export KUBECONFIG=~/.kube/config
          kubectl get pods -o wide
